### ISSUE TITLE
Ability Checks should have a multiplier

### ISSUE THREAD

**Issue by Pantsorama** [bayne7400/Gamma-World-2E#4]
From Pg 7 In the rules:

In many cases, the GM will need to modify the check by having the character check against a multiple of the appropriate Attribute. For example, leaping a 4-meter fissure might require a check versus DX x 5 since there should be a chance of not making the jump (but a greater chance of making it). In this case, a character with a DX of 12 would have to roll 60 or less (12 x 5 = 60) to make the jump. There would be a 40% chance of failing. As a rule, the harder the task, the lower the multiple.

**Comment by bayne7400** [comment]
thats what the Target number is for
